a=int(input("enter the no iterations: "))
for i in range(a):
    name=input("enter the passenger name: ")
    date=input("enter the date of reservation: ")
    age=int(input("enter the age of passenger: "))
    departure=input("enter the departing station: ")
    arrival=input("enter the arriving station: ")
    gender=input("enter the gender of the passenger: ")
    print("hi")
print("name of the passenger: ",name)
print("date of the reservation: ",date)
print("enter the age of the passenger: ",age)
print("enter the departing station: ",departure)
print("enter the arriving station: ",arrival)
print("enter the gender of the passenger: ",gender)
print("thank you !!")
print("visit again ")
print("happy journey !!")